# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
      - name: aws-cli
        env:
              AWS_CLI_AUTO_PROMPT: on-partial
        before: |
              cd /workspace
              cd /workspace
              sudo apt-get update
              sudo apt-get install -y python3
              sudo ln -s /usr/bin/python3 /usr/bin/python  # Add this line
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
              cd /workspace/AWS-Examples
